### PR TITLE
feat: Added local images support

### PR DESCRIPTION
**Pull request by kkomelin**
## Checklist

- [x] Tests (if applicable)
- [x] Documentation (if applicable)
- [x] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

### CODE REVIEW

**Comment by kkomelin** [comment]
Hi @nd0ut,

I've added support for local images (relative paths). 

How it works:
1) If the `NEXT_PUBLIC_UPLOADCARE_APP_BASE_PATH` environment variable is set, convert the relative path to the absolute one and pass it to the proxy.
2) If the `NEXT_PUBLIC_UPLOADCARE_APP_BASE_PATH` environment variable is not set, return it AS IS.

Could you please quickly review the changes?

**Comment by kkomelin** [comment]
@nd0ut I've merged the PR without review. Feel free to send your improvements through PRs or bug reports if any.

**Comment by nd0ut** [comment]
@kkomelin missed your mention, sorry

@shipjs prepare

**Comment by nd0ut** [comment]
@shipjs prepare

**Comment by kkomelin** [comment]
> @kkomelin missed your mention, sorry

@nd0ut That's totally Okay. Thanks

**Comment by kkomelin** [comment]
@shipjs prepare

**Pull request merged**
